# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLoops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100)),
                ('mssg_freq', models.IntegerField()),
                ('mins_to_mssg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=300)),
                ('active_loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='productivity_bot.ActiveLoops')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('sheet_created', models.BooleanField()),
                ('sheet_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activeloops',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_loop', to='productivity_bot.Users'),
        ),
    ]
