# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_bot', '0002_auto_20180615_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sheet_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sheet_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
