# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_bot', '0004_remove_activeloops_webhook_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
