# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_bot', '0005_auto_20180618_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
