# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_bot', '0006_auto_20180625_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeloops',
            name='mins_to_mssg',
        ),
        migrations.RemoveField(
            model_name='activeloops',
            name='mssg_freq',
        ),
    ]
